In [1]:
import copy
import numpy as np

## <i>Preparing the data</i>

In [2]:
# generate 1000 random 3d matrices for creating the dataset (1000 random 3*3 pixels images)
matrices = []
n = 1000
for _ in range(n):
    matrices.append(np.random.randint(0, 255, size=(3, 3, 3)))

In [3]:
# for example the first images is:
matrices[0]

array([[[222,  17, 129],
        [  0, 201, 236],
        [165, 137, 166]],

       [[147,  30,  60],
        [ 57,  93,   6],
        [ 10, 109,  33]],

       [[219,  35, 157],
        [ 26, 199, 113],
        [149, 230, 127]]])

In [4]:
# and the last is:
matrices[n-1]

array([[[  8,  89, 116],
        [217,  21, 195],
        [239,  22, 150]],

       [[243, 120,  93],
        [193, 108,  72],
        [127,  25, 186]],

       [[105, 232, 220],
        [ 34, 182, 207],
        [165, 189, 233]]])

## <i>Creating the dataset</i>

In [5]:
# getting a deep copy if the images matrices
data = copy.deepcopy(matrices)

# reshape each 3d matrix in the data for the dataset
for image in data:
    image.shape = (3, 9)

# each middle value in the arrays of an image change it position to the last
for image in data:
    for mat in image:
        temp = mat[4]
        mat[4] = mat[8]
        mat[8] = temp

In [9]:
data

[array([[222,  17, 129,   0, 166, 236, 165, 137, 201],
        [147,  30,  60,  57,  33,   6,  10, 109,  93],
        [219,  35, 157,  26, 127, 113, 149, 230, 199]]),
 array([[250,  23, 226, 215,   6, 103, 121, 100, 228],
        [134, 221,  38,  56, 113, 100, 189, 122,  52],
        [ 48, 251, 152, 143, 163,  58,  47, 185,  65]]),
 array([[  3,  39, 123, 128,   4, 167,  54,   2,   8],
        [ 76,  13, 125,  39, 200, 122, 193, 237, 104],
        [101, 119,   6,  40, 197, 157,  50, 195, 208]]),
 array([[188, 178, 103, 209,  79, 136,  30, 191, 254],
        [253, 110,  84,  41,  46,  45,  69, 235,  51],
        [ 70, 141, 116, 184, 173, 199, 224,  56, 150]]),
 array([[201,  36, 215,  16, 141,  84,   0, 123, 131],
        [  0, 147, 246, 152, 218, 168,  79, 117,  44],
        [160, 209,  46, 104,  46,  86, 242,  69,  23]]),
 array([[ 30, 160, 119, 199, 170, 111,  66, 100, 136],
        [201, 120, 193, 202, 127, 158, 185,  10, 242],
        [ 75, 149,  56, 189, 224, 223,  63,   7, 180]])