In [39]:
import copy
import numpy as np

## <i>Preparing the data</i>

In [40]:
# generate 1000 random 3d matrices for creating the dataset (1000 random 3*3 pixels images)
matrices = []
n = 1000
for _ in range(n):
    matrices.append(np.random.randint(0, 255, size=(3, 3, 3)))

In [46]:
pixels = 3

i = np.random.randint(0, 255)
j = np.random.randint(0, 255)

a = np.full((pixels, pixels), i)
b = np.random.randint(100, 200, size=(pixels, pixels))
c = np.full((pixels, pixels), j)
m = [a, b, c]
m = np.array(m)
print(m)

from PIL import Image

img = Image.fromarray(m, 'RGB')
img.show()




[[[131 131 131]
  [131 131 131]
  [131 131 131]]

 [[134 189 173]
  [159 101 129]
  [142 169 105]]

 [[229 229 229]
  [229 229 229]
  [229 229 229]]]


In [48]:
pixels = 50

i = np.random.randint(0, 255)
j = np.random.randint(0, 255)

a = np.full((pixels, pixels), i)
b = np.random.randint(100, 200, size=(pixels, pixels))
c = np.full((pixels, pixels), j)
m = [a, b, c]
m = np.array(m)
print(m)

from PIL import Image

img = Image.fromarray(m, 'RGB')
img.show()


[[[194 194 194 ... 194 194 194]
  [194 194 194 ... 194 194 194]
  [194 194 194 ... 194 194 194]
  ...
  [194 194 194 ... 194 194 194]
  [194 194 194 ... 194 194 194]
  [194 194 194 ... 194 194 194]]

 [[194 177 121 ... 142 176 164]
  [178 131 107 ... 198 134 184]
  [191 176 111 ... 167 103 121]
  ...
  [175 198 123 ... 104 181 130]
  [179 182 125 ... 139 199 148]
  [107 140 162 ... 134 148 163]]

 [[ 11  11  11 ...  11  11  11]
  [ 11  11  11 ...  11  11  11]
  [ 11  11  11 ...  11  11  11]
  ...
  [ 11  11  11 ...  11  11  11]
  [ 11  11  11 ...  11  11  11]
  [ 11  11  11 ...  11  11  11]]]


In [71]:
from PIL import Image
import numpy as np

w, h = 512, 512
data = np.zeros((h, w, 3), dtype=np.uint8)
for i in range(len(data)):
    for j in range(i):
        data[i][j][0] = np.random.randint(130,150)
        data[i][j][1] = 90
        data[i][j][1] = 50

# data[0:256, 0:256] = [np.random.randint(100,200), 0, 0] # red patch in upper left
img = Image.fromarray(data, 'RGB')
img.save('my.png')
img.show()

In [8]:
# for example the first images is:
matrices[0]

array([[[165,  63, 216],
        [117, 253, 169],
        [ 53, 227,  99]],

       [[ 28,  92,  33],
        [230, 108, 104],
        [251, 169, 208]],

       [[206,  13, 251],
        [154,   2, 179],
        [197, 160, 235]]])

In [9]:
# and the last is:
matrices[n-1]

array([[[113, 102, 135],
        [215,  62, 199],
        [178, 243, 167]],

       [[208, 244,  50],
        [212, 152,  64],
        [163, 215,  41]],

       [[128, 144, 113],
        [118,  20,  73],
        [  3, 167, 216]]])

## <i>Creating the dataset</i>

In [11]:
# getting a deep copy if the images matrices
data = copy.deepcopy(matrices)

# reshape each 3d matrix in the data for the dataset
for image in data:
    image.shape = (3, 9)

# each middle value in the arrays of an image change it position to the last
for image in data:
    for mat in image:
        # swaping
        temp = mat[4]
        i = 8
        while i > 4:
            mat[i-1] = mat[i]
            i -= 1
        mat[8] = temp


In [12]:
data

[array([[165,  63, 216, 117,  99,  99,  99,  99, 253],
        [ 28,  92,  33, 230, 208, 208, 208, 208, 108],
        [206,  13, 251, 154, 235, 235, 235, 235,   2]]),
 array([[148, 145,   9, 208, 220, 220, 220, 220, 129],
        [ 74,   1,  99, 127, 207, 207, 207, 207, 184],
        [151,  40,  58,  76, 195, 195, 195, 195,  83]]),
 array([[ 49, 237, 225,  76, 177, 177, 177, 177, 204],
        [227, 126, 240, 239, 244, 244, 244, 244,  94],
        [ 95, 229, 201, 127, 223, 223, 223, 223, 110]]),
 array([[111, 218,  96, 208,  19,  19,  19,  19,  81],
        [123, 239,  37,  55,  49,  49,  49,  49,  90],
        [ 51, 147, 246,  35, 138, 138, 138, 138, 234]]),
 array([[ 16,  64, 162, 161, 109, 109, 109, 109,  12],
        [185, 182,  23,  34, 131, 131, 131, 131, 120],
        [ 15, 169, 252,   2, 172, 172, 172, 172, 204]]),
 array([[157, 237, 243, 189,  71,  71,  71,  71, 188],
        [ 34,   2,  28,  27, 147, 147, 147, 147, 229],
        [ 38,  13, 222,   5, 203, 203, 203, 203, 140]])

In [19]:
from PIL import Image

img = Image.fromarray(matrices[0], 'RGB')
img.show()