In [1]:
import copy
import numpy as np

## <i>Preparing the data</i>

In [2]:
# generate 1000 random 3d matrices for creating the dataset (1000 random 3*3 pixels images)
matrices = []
n = 1000
for _ in range(n):
    matrices.append(np.random.randint(0, 255, size=(3, 3, 3)))

In [3]:
# for example the first images is:
matrices[0]

array([[[ 71, 221, 184],
        [166, 189, 165],
        [ 93, 189,  58]],

       [[ 13,  81,  86],
        [168, 130,  12],
        [  4, 242,  88]],

       [[236, 251, 134],
        [  2, 120,  60],
        [ 62, 143, 145]]])

In [4]:
# and the last is:
matrices[n-1]

array([[[ 22,  25,  54],
        [ 17, 154, 102],
        [209, 142,  11]],

       [[204,  72, 204],
        [ 63,   0,  45],
        [ 32, 122,  58]],

       [[207,  96, 126],
        [ 47,  86,  87],
        [174,  42, 126]]])

## <i>Creating the dataset</i>

In [5]:
# getting a deep copy if the images matrices
data = copy.deepcopy(matrices)

# reshape each 3d matrix in the data for the dataset
for image in data:
    image.shape = (3, 9)

# each middle value in the arrays of an image change it position to the last
for image in data:
    for mat in image:
        temp = mat[4]
        mat[4] = mat[8]
        mat[8] = temp

In [6]:
data

[array([[ 71, 221, 184, 166,  58, 165,  93, 189, 189],
        [ 13,  81,  86, 168,  88,  12,   4, 242, 130],
        [236, 251, 134,   2, 145,  60,  62, 143, 120]]),
 array([[ 95, 196, 162,  50,  20, 241, 177,   7,   2],
        [ 23,  28, 127, 115,  11, 245, 221, 238,  97],
        [184, 107, 197, 201, 225,  45, 169,   8,  90]]),
 array([[250, 149, 228, 113, 167, 165, 252, 185,  15],
        [203,  59, 172, 109, 165, 239,  75,  82, 113],
        [212, 191, 164, 171,  61,  13, 183, 144, 190]]),
 array([[ 58, 250, 232, 173, 164,  44,  54,   6,  90],
        [160,  84,  54, 202,  87, 157,  48, 124,  65],
        [ 76,  72,  40,  64, 208, 198, 103,  84,  70]]),
 array([[ 51,  34, 208, 107,  18, 212, 165, 158, 252],
        [ 47, 152, 153,  24, 202,  59,  17,  59, 124],
        [174,  52, 166, 125,  42, 133,  89, 205,  82]]),
 array([[ 72, 110, 148, 230,  43, 163, 185,   9, 183],
        [251,  85, 242,  82, 123, 232, 202,  14, 106],
        [135, 202, 184,  17, 229, 206, 108, 171, 241]])

In [12]:
from PIL import Image

img = Image.fromarray(matrices[3],'RGB')
img.save('my.png')