In [15]:
# import tensorflow as tf
from data_generators import gen_frm_pic
from util_functions import util_functions

INDEX_TRGT = 4
INDEX_END = 8
ROW_SHAPE = (1,9)

In [16]:
data = gen_frm_pic.gen_frm_pic.generate()

In [17]:
# red channel data
r_data = []

# green channel data
g_data = []

# blue channel data
b_data = []
for image in data:
    for i in range(3):

        if i == 0:
            r_temp = image[i].reshape(ROW_SHAPE)[0]
            util_functions.swap(r_temp, INDEX_TRGT, INDEX_END)
            r_data.append(r_temp)

        if i == 1:
            g_temp = image[i].reshape(ROW_SHAPE)[0]
            util_functions.swap(g_temp, INDEX_TRGT, INDEX_END)
            g_data.append(g_temp)
            
        if i == 2:
            b_temp = image[i].reshape(ROW_SHAPE)[0]
            util_functions.swap(b_temp, INDEX_TRGT, INDEX_END)
            b_data.append(b_temp)

data = [r_data, g_data, b_data]

[188 189 184 188 189 184 188 189 184]
[188 189 184 188 189 184 188 189 184]
[188 189 184 188 189 184 188 189 184]
[188 189 184 189 190 185 189 190 185]
[188 189 184 189 190 185 189 190 185]
[188 189 184 188 189 184 189 190 185]
[189 190 185 189 190 185 190 191 186]
[189 190 185 189 190 185 189 190 185]
[189 190 185 189 190 185 189 190 185]
[190 191 186 190 191 186 190 191 186]
[189 190 185 190 191 186 190 191 186]
[189 190 185 189 190 185 189 190 185]
[190 191 186 190 191 186 190 191 186]
[190 191 186 190 191 186 190 191 186]
[190 191 186 190 191 186 190 191 186]
[191 192 187 191 192 187 191 192 187]
[190 191 186 191 192 187 191 192 187]
[190 191 186 190 191 186 190 191 186]
[191 192 187 191 192 187 190 191 186]
[190 191 186 190 191 186 190 191 186]
[190 191 186 190 191 186 190 191 186]
[190 191 186 190 191 186 190 191 186]
[190 191 186 190 191 186 190 191 186]
[190 191 186 190 191 186 190 191 186]
[192 193 188 192 193 188 192 193 188]
[191 192 187 191 192 187 191 192 187]
[191 192 187