In [117]:
import tensorflow as tf
from data_generators import gen_frm_pic
from util_functions import util_functions

TRGT = 4
END = 8

In [118]:
data = gen_frm_pic.gen_frm_pic.generate()

In [119]:
# red channel data
r_data = []

# green channel data
g_data = []

# blue channel data
b_data = []
for image in data:
    for i in range(3):

        if i == 0:
            r_temp = image[i].reshape((1, 9))[0]
            util_functions.swap(r_temp, TRGT, END)
            r_data.append(r_temp)

        if i == 1:
            g_temp = image[i].reshape((1, 9))[0]
            util_functions.swap(g_temp, TRGT, END)
            g_data.append(g_temp)
            
        if i == 2:
            b_temp = image[i].reshape((1, 9))[0]
            util_functions.swap(b_temp, TRGT, END)
            b_data.append(b_temp)

data = [r_data, g_data, b_data]

In [120]:
data

[[array([188, 189, 184, 188, 184, 184, 188, 189, 189], dtype=uint8),
  array([188, 189, 184, 189, 185, 185, 189, 190, 190], dtype=uint8),
  array([189, 190, 185, 189, 186, 185, 190, 191, 190], dtype=uint8),
  array([190, 191, 186, 190, 186, 186, 190, 191, 191], dtype=uint8),
  array([190, 191, 186, 190, 186, 186, 190, 191, 191], dtype=uint8),
  array([191, 192, 187, 191, 187, 187, 191, 192, 192], dtype=uint8),
  array([191, 192, 187, 191, 186, 187, 190, 191, 192], dtype=uint8),
  array([190, 191, 186, 190, 186, 186, 190, 191, 191], dtype=uint8),
  array([192, 193, 188, 192, 188, 188, 192, 193, 193], dtype=uint8),
  array([192, 193, 188, 192, 188, 188, 192, 193, 193], dtype=uint8),
  array([192, 193, 188, 192, 187, 188, 191, 192, 193], dtype=uint8),
  array([191, 192, 187, 191, 187, 187, 191, 192, 192], dtype=uint8),
  array([192, 193, 188, 192, 188, 188, 192, 193, 193], dtype=uint8),
  array([192, 193, 188, 192, 188, 188, 192, 193, 193], dtype=uint8),
  array([192, 193, 188, 192, 188, 