In [1]:
import tensorflow as tf
import numpy as np
from data_generators import gen_frm_pic
from util_functions import util_functions

INDEX_TRGT = 4
INDEX_END = 8
ROW_SHAPE = (1,9)

In [2]:
data = gen_frm_pic.gen_frm_pic.generate()

In [3]:
# red channel data
r_data = []

# green channel data
g_data = []

# blue channel data
b_data = []
for image in data:
    for i in range(3):

        if i == 0:
            r_temp = image[i].reshape(ROW_SHAPE)[0]
            util_functions.swap(r_temp, INDEX_TRGT, INDEX_END)
            r_data.append(r_temp)

        if i == 1:
            g_temp = image[i].reshape(ROW_SHAPE)[0]
            util_functions.swap(g_temp, INDEX_TRGT, INDEX_END)
            g_data.append(g_temp)
            
        if i == 2:
            b_temp = image[i].reshape(ROW_SHAPE)[0]
            util_functions.swap(b_temp, INDEX_TRGT, INDEX_END)
            b_data.append(b_temp)

In [4]:
data = [r_data, g_data, b_data]
print(len(data))
print(len(r_data))
print(len(g_data))
print(len(b_data))

3
17876
17876
17876


In [5]:
train_data = [data[0][0:10000], data[1][0:10000], data[2][0:10000]]
test_data  = [data[0][3000:13000], data[1][3000:13000], data[2][3000:13000]]
validation_data = [data[0][13000:16000], data[1][13000:16000], data[2][13000:16000]]

In [6]:
# len(train_data)
# train_X = np.array()
# for channel in train_data:
    # print('channel 1 is: ', channel)

In [7]:

# train_X will contain 30000 rows - each 3 lines near each other is three channels of one pixel
# for example train_x[0], train_x[1] and train_x[2] is the channles data for a single pixel (red, blud, green)
train_X = []

# train_y will contatin 30000 desirable predicted values - label value for each x row (each channel of pixel)
train_y = []

for i in range(10000):
    # red channel data
    train_X.append(train_data[0][i][0:INDEX_END])
    train_y.append(train_data[0][i][INDEX_END:INDEX_END+1])

    # green channel data
    train_X.append(train_data[1][i][0:INDEX_END])
    train_y.append(train_data[1][i][INDEX_END:INDEX_END+1])

    # blue channel data
    train_X.append(train_data[2][i][0:INDEX_END])
    train_y.append(train_data[2][i][INDEX_END:INDEX_END+1])


print(len(train_X))
# data_x = np.array([[1,28,4],[1,60,34],[1,25,3],[0,54,20],[0,24,2],[0,39,12],[0,30,4],[1,36,10],[1,26,1],[0,44,9]])
# data_y = np.array([1,1,1,1,1,1,1,0,0,0])

# print(w,b)
# print("User [1, 49, 8] prob of working: ", h(np.array([[1, 49, 8]]),w,b))
# print("User [0, 29, 3] prob of working: ", h(np.array([[0, 29, 3]]),w,b))
# print("User [1, 29, 3] prob of working: ", h(np.array([[1, 29, 3]]),w,b))


30000


In [10]:
def h(x, w, b):
    return 1 / (1 + np.exp(-(np.dot(x, w) + b)))

w = np.array([0.,0,0,0,0,0,0,0])
b = 0
alpha = 0.001
for iteration in range(100000):
    gradient_b = np.mean(1 * ((h(train_X, w, b)) - train_y))
    gradient_w = np.dot((h(train_X, w, b) - train_y), train_X) * 1 / len(train_y)
    b -= alpha * gradient_b
    w -= alpha * gradient_w


ValueError: non-broadcastable output operand with shape (8,) doesn't match the broadcast shape (30000,8)

In [ ]:
train_y

[array([189], dtype=uint8),
 array([189], dtype=uint8),
 array([189], dtype=uint8),
 array([190], dtype=uint8),
 array([190], dtype=uint8),
 array([189], dtype=uint8),
 array([190], dtype=uint8),
 array([190], dtype=uint8),
 array([190], dtype=uint8),
 array([191], dtype=uint8),
 array([191], dtype=uint8),
 array([190], dtype=uint8),
 array([191], dtype=uint8),
 array([191], dtype=uint8),
 array([191], dtype=uint8),
 array([192], dtype=uint8),
 array([192], dtype=uint8),
 array([191], dtype=uint8),
 array([192], dtype=uint8),
 array([191], dtype=uint8),
 array([191], dtype=uint8),
 array([191], dtype=uint8),
 array([191], dtype=uint8),
 array([191], dtype=uint8),
 array([193], dtype=uint8),
 array([192], dtype=uint8),
 array([192], dtype=uint8),
 array([193], dtype=uint8),
 array([192], dtype=uint8),
 array([192], dtype=uint8),
 array([193], dtype=uint8),
 array([192], dtype=uint8),
 array([192], dtype=uint8),
 array([192], dtype=uint8),
 array([192], dtype=uint8),
 array([192], dtype=